model:
  text_model_name: "meta-llama/Llama-3.1-8B-Instruct"
  audio_model_name: "openai/whisper-medium"
  use_lora: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  audio_use_lora: false
  projector_hidden_size: 1024
  projector_output_size: 4096
  projector_dropout: 0.1
  audio_sample_rate: 16000
  audio_max_length: 30.0
  torch_dtype: "bfloat16"
  device_map: "auto"

training:
  batch_size: 4
  gradient_accumulation_steps: 1
  learning_rate: 1e-4
  weight_decay: 0.01
  warmup_steps: 100
  max_steps: 1000
  save_steps: 500
  eval_steps: 100
  logging_steps: 10
  optimizer: "adamw_torch"
  lr_scheduler: "cosine"
  fp16: true
  bf16: false
  output_dir: "./checkpoints"
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  logging_dir: "./logs"
  report_to: "tensorboard"

data:
  train_dataset_path: "./data/train_dataset.json"
  eval_dataset_path: "./data/eval_dataset.json"
  task: null  # null이면 멀티태스크 학습, 특정 태스크명을 지정하면 단일 태스크 학습
  max_audio_length: 30.0
  sample_rate: 16000
  num_workers: 4
  template_kwargs: {}
